# Generated by Django 5.0.1 on 2024-03-01 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_tax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name_plural': 'Tax'},
        ),
    ]
